name: openaiproject
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - annotated-types==0.6.0
      - anyio==4.3.0
      - blinker==1.8.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - distro==1.9.0
      - Flask==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - itsdangerous==2.2.0
      - Jinja2==3.1.4
      - MarkupSafe==2.1.5
      - openai==1.29.0
      - pocket==0.3.6
      - pydantic==2.7.1
      - pydantic_core==2.18.2
      - python-dotenv==1.0.1
      - requests==2.31.0
      - setuptools==69.5.1
      - sniffio==1.3.1
      - tqdm==4.66.4
      - typing-extensions==4.11.0
      - urllib3==2.2.1
      - Werkzeug==3.0.3
      - wheel==0.43.0
      - sqlalchemy==2.0.20
      - loguru==0.7.0
      - firecrawl
