name: Python Linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Run flake8
        run: flake8 .
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check-only .
      - name: Run mypy
        run: mypy .
